name: Build Artifacts

on:
  push:
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    permissions:
       contents: write
       actions: write

    steps:
      - uses: actions/checkout@main

      - name: Setting up Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Setup everything
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
        shell: cmd

      - name: Setup HXCPP dev commit
        run: |
          cd .haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd ../../../../..

      - name: Compile FnFork
        run: haxe build.hxml

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: FnFork-Windows
          path: bin/cpp/FnFork.exe
  
  buildLinux:
    runs-on: ubuntu-latest

    permissions:
       contents: write
       actions: write

    steps:
      - uses: actions/checkout@main

      - name: Setting up Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Setup everything
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
        shell: cmd

      - name: Setup HXCPP dev commit
        run: |
          cd .haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd ../../../../..

      - name: Compile FnFork
        run: haxe build.hxml

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: FnFork-Linux
          path: bin/cpp/FnFork