name: Build Artifacts

on:
  push:
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    permissions:
       contents: write
       actions: write

    steps:
      - uses: actions/checkout@main

      - name: Setting up Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Setup everything
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp

      - name: Compile FnFork
        run: haxe build.hxml

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: FnFork-Windows
          path: bin/cpp/FnFork.exe
  
  buildLinux:
    runs-on: ubuntu-latest

    permissions:
       contents: write
       actions: write

    steps:
      - uses: actions/checkout@main

      - name: Setting up Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Setup everything
        run: |
          mkdir ~/haxelib && haxelib setup ~/haxelib
          haxelib install hxcpp

      - name: Compile FnFork
        run: haxe build.hxml

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: FnFork-Linux
          path: bin/cpp/FnFork